on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: step 1
        run: echo "Hello World from SJ"

      - name: step 2
        run: df -hT

      - name: step 3
        run: |
          pwd
          date
          hostname
          ls -la
          whoami
