name: WF-SJ
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Running command
      run: |
        date
        sleep 30
  job2:
    need job1
    runs-on: ubuntu-latest
    steps:
    - name: running other command
      run: |
        date
        pwd
        sleep 25
  job3:
    needs:
    - job1
    - job2
    runs-on: ubuntu-latest
    steps:
    - name: running commands
      run: echo "testing completed "
  
